// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDiN8LY_8sXpd3_2szquda70cRL54dzkIc',
//     appId: '1:546481913027:web:2cba9f09a32c47a014f676',
//     messagingSenderId: '546481913027',
//     projectId: 'safe-talk-37a74',
//     authDomain: 'safe-talk-37a74.firebaseapp.com',
//     storageBucket: 'safe-talk-37a74.firebasestorage.app',
//     measurementId: 'G-CV462BM772',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBUWB50Fg_Azx057ZxgAcwpyTkeLehOtU0',
//     appId: '1:546481913027:android:b86a0ba2a51b9c5314f676',
//     messagingSenderId: '546481913027',
//     projectId: 'safe-talk-37a74',
//     storageBucket: 'safe-talk-37a74.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCCw5sdIKf2FoTfGCQt6vwkr7EqxgsMNgU',
//     appId: '1:546481913027:ios:13ff2a642dd6316614f676',
//     messagingSenderId: '546481913027',
//     projectId: 'safe-talk-37a74',
//     storageBucket: 'safe-talk-37a74.firebasestorage.app',
//     iosBundleId: 'com.example.safetalk',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCCw5sdIKf2FoTfGCQt6vwkr7EqxgsMNgU',
//     appId: '1:546481913027:ios:13ff2a642dd6316614f676',
//     messagingSenderId: '546481913027',
//     projectId: 'safe-talk-37a74',
//     storageBucket: 'safe-talk-37a74.firebasestorage.app',
//     iosBundleId: 'com.example.safetalk',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDiN8LY_8sXpd3_2szquda70cRL54dzkIc',
//     appId: '1:546481913027:web:ca7430a0f79c181514f676',
//     messagingSenderId: '546481913027',
//     projectId: 'safe-talk-37a74',
//     authDomain: 'safe-talk-37a74.firebaseapp.com',
//     storageBucket: 'safe-talk-37a74.firebasestorage.app',
//     measurementId: 'G-06QBC86NJE',
//   );
// }
